services:
  - type: web
    name: assignment-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn Assignment_Tracker.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Assignment_Tracker.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DISABLE_COLLECTSTATIC
        value: 0
    staticPublishPath: staticfiles
